### ISSUE TITLE
Requester content reader not working correctly

### ISSUE THREAD

**Issue by jgoyvaerts** [Yousei9/LTN-Content-Reader#10]
So I placed a requester content reader, set it to network 4 and it correctly reads the requests on that network (in my test setup: -1000 heat shielding).

However, after several ticks (roughly 3-4 seconds), the amount the Requester content reader outputs increases, so it goes from -1000 to -2000, -3000, etc. It just keeps going. My station is still requesting -1000.

Is this a known bug? 

Some screenshots to illustrate:
![image](https://user-images.githubusercontent.com/1125884/198905908-dca9c4be-1a39-4282-b298-ec3ef440d1f7.png)
![image](https://user-images.githubusercontent.com/1125884/198905917-95ed638e-c463-4bdd-8819-fdff6cb28d2d.png)

**Comment by Yousei9** [comment]
Enable LTN Debug log and post factorio-current.log

**Comment by jgoyvaerts** [comment]
After looking at the log myself I found the problem. I was using the content reader to feed info to another network, and the network signal of the reader (4) was being added to the network signal of the station I was feeding it into (2), which in turn meant the station was network 6 and thus also it's requests were being counted, causing a loop.

Filtering out the network signal of the content reader with a decider combinator before linking it to the station fixed the issue.

Thanks for the help.
